This Python implementation can be run in three different ways:

1. Simply use our wrapper script - run.sh and pass it the parameters in order
		<INTEGRATED-DATASET-FILE> is the name of CSV file
		<min_sup> is the value of minimun support
		<min_conf> is the value of minimun confidence

Example : sh run.sh data/INTEGRATED-DATASET.csv 0.02 0.1

2. Use python directly. Call python extract_Rule.py and pass it the parameters in order
		<INTEGRATED-DATASET-FILE> is the name of CSV file
		<min_sup> is the value of minimun support
		<min_conf> is the value of minimun confidence
		<output-file> is the output of the large itemsets and rules.
		
Example: python src/extract_Rule.py data/INTEGRATED-DATASET.csv 0.02 0.1 output.txt

3. YOu can run extract_Rule.py in Pycharm and you will see the output in output file after successfully finishing it.
(For changing data set goto: RUN-->Edit configuration --> in Configuration tab change the Script Perameters )